### ISSUE TITLE
NPM WARN 

### ISSUE THREAD

**Issue by ghost** [FreeCodeCampMontevideo/fccmontevideo.com#35]
Reinstalando los paquetes del repo got this:
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

Todo funciona bien pero lo notifico por las dudas.

**Comment by MatiasVerdier** [comment]
Es normal, no pasa nada.
Gracias.
